### ISSUE TITLE
As developer, I want a test environment deployed of the API

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sharing-configs#31]
* [x] Get server (@joeribekker )
* [x] Get domain (@joeribekker )
* [x] Create deployment repo
* [x] Create playbook (see our Ansible Common Ground playbook)

**Comment by annashamray** [comment]
The deployment repo - https://github.com/maykinmedia/sharing-configs-api-deployment/

**Comment by annashamray** [comment]
The deployed API - https://sharing-configs-api.test.maykin.opengem.nl/
