### ISSUE TITLE
As a developer I want examples how to use the lib

### ISSUE THREAD

**Issue by annashamray** [maykinmedia/sharing-configs#42]
### Thema / Theme

Other

### Description

* [x] Please update "Usage" section of the README file with examples how to use the library for import and export
* [x] Please add more information in the docstrings of `get_sharing_configs_import_data` and `get_sharing_configs_export_data` 

### Example

As example we're going to use "themes", that changes the appearance of the Django admin.
For simplicity, a color theme has just a few (css) properties and a name. This "theme" can be exported and imported via this library.

* [x] Add a "Theme" model, with a fields: `name, primary, accent, secondary, primary-fg`. You can use [Django Colorfield](https://pypi.org/project/django-colorfield/)
* [x] Add a "Configuration" model (can be [django-solo](https://github.com/lazybird/django-solo) model but doesn't have to) with 1 dropdown field: `theme`
* [x] The selected theme in the configuration, should be loaded in the Django admin `base_site.html` template. This can be done with a Django context processor to load in the theme (for simplicity) and with some inline `<style>` to set the theme (see screenshots: `:root`)

We can accomplish this with minimal effort:

**Theme settings:**
![image](https://user-images.githubusercontent.com/96970/168778446-fa0cd74a-bdd9-45a1-9e67-8c0df304b7e0.png)

**Themes:**
![image](https://user-images.githubusercontent.com/96970/168776843-adc58355-55f3-4ad5-a4ae-e70e8e385cb0.png)
![image](https://user-images.githubusercontent.com/96970/168776970-4d26e50f-516a-4112-9f64-3f8fb964d8eb.png)

**Comment by joeribekker** [comment]
See for example: https://github.com/maykinmedia/django-dbcache-fields#usage
