### ISSUE TITLE
Bugs discovered while integrating with objecttypes api

### ISSUE THREAD

**Issue by annashamray** [maykinmedia/sharing-configs#50]
### Describe the bug

**Import:**
* [x] `get_sharing_configs_import_data` doesn't have `content` parameter. It's impossible to import file without knowing its content
* [x] `get_sharing_configs_import_data` is never called inside `SharingConfigsImportMixin` , so the hook designed by the lib user is actually never used
* [x] in the `import.html` there is a url `admin:auth_user_import` which doesn't not exist 
* [x] in the `import.html` there is a url `admin:auth_user_ajax` which doesn't exist
* [x] in `get_imported_folders_choices` for import you don't need permission 'read'. You need to show folders with all permissions, not read-only. 
* [x] `get_list_folders_url`, `get_folder_files_url`, `get_import_url`, `get_export_url` in `SharingConfigsClient`  miss 'config' part of the url

**Export:** 
* [x] In `sharing_configs_export_view` `obj.username` is used which doesn't exist 
* [x] Why is `permission` param in `SharingConfigsClient.get_folders` treated as dict when you fill it with string?
* [x] `content` is not base64 encoded, which can't be processed by API
* [x] (not crit) On the export page when there is a validation error the header becomes "Import from community" (see the screenshot below)
* [x] (not crit) On the export page the validation error starts with: "Import of object failed: "

### Additional context
![image](https://user-images.githubusercontent.com/47745906/168825509-5740ae2a-3871-4152-a3e4-38502ecfa839.png)

**Comment by frekkenSnork** [comment]
Almost there but need to fix some tests
